-- AlterEnum
BEGIN;
CREATE TYPE "AuditAction_new" AS ENUM ('CLAIM_SUBMITTED', 'CLAIM_REVIEWED', 'CLAIM_APPROVED', 'CLAIM_DENIED', 'REPORT_SUBMITTED', 'REPORT_UPDATED', 'REPORT_LINKED', 'HANDOVER_COMPLETED', 'AUTH_LOGIN', 'SNAPSHOT_DISMISSED', 'SNAPSHOT_RESTORED', 'USER_CREATED', 'USER_UPDATED', 'USER_ROLE_CHANGED', 'USER_DISABLED', 'USER_ENABLED', 'USER_PASSWORD_RESET', 'SYSTEM_SETTINGS_UPDATED');
ALTER TABLE "AuditLog" ALTER COLUMN "action" TYPE "AuditAction_new" USING ("action"::text::"AuditAction_new");
ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";
ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
DROP TYPE "public"."AuditAction_old";
COMMIT;

-- AlterEnum
ALTER TYPE "ReportStatus" ADD VALUE 'CANCELLED';

